language: cpp

jobs:
 include:
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=56
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=56 USE_CMAKE=true
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=59 USE_CMAKE=true
  - os: linux
    dist: focal
    compiler: gcc
    env:
     - QT_BASE=512 USE_CMAKE=true
  - os: linux
    dist: focal
    compiler: gcc
    env:
     - QT_BASE=515
  - os: linux
    dist: focal
    compiler: gcc
    env:
     - QT_BASE=515 USE_CMAKE=true

before_install:
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt563-xenial -y; fi
  - if [ "$QT_BASE" = "59" ]; then sudo add-apt-repository ppa:beineri/opt-qt597-xenial -y; fi
  - if [ "$QT_BASE" = "512" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.12.10-focal -y; fi
  - if [ "$QT_BASE" = "515" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-focal -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi

install:
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi
  - if [ "$QT_BASE" = "59" ]; then sudo apt-get install -qq qt59base; source /opt/qt59/bin/qt59-env.sh; fi
  - if [ "$QT_BASE" = "512" ]; then sudo apt-get install -qq qt512base; source /opt/qt512/bin/qt512-env.sh; fi
  - if [ "$QT_BASE" = "515" ]; then sudo apt-get install -qq qt515base; source /opt/qt515/bin/qt515-env.sh; fi

script:
  - git submodule update --init --recursive

  # build library and binary
  - mkdir ./build && cd ./build
  - if [ "$USE_CMAKE" = "true" ]; then
      cmake --version;
      cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF ..;
      make;
    else
      qmake -v;
      qmake ../qtcsv-example.pro CONFIG+=release LIBS+=-L../qtcsv;
      make;
    fi

  # Execute binary file
  - cd ./example
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/../qtcsv
  - ./example

notifications:
  email: true
