version: "{build}"

init:
- git config --global core.autocrlf input

environment:
  matrix:
  - QT5: C:\Qt\5.6.3\mingw49_32
    MINGW: C:\Qt\Tools\mingw530_32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - QT5: C:\Qt\5.9\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - QT5: C:\Qt\5.12\mingw73_32
    MINGW: C:\Qt\Tools\mingw730_32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

matrix:
  fast_finish: true

before_build:
- set PATH=%MINGW%\bin;%QT5%\bin;%PATH%
- git submodule update --init --recursive

build_script:
- mkdir .\build
- cd .\build
- qmake -v
- qmake ..\qtcsv\qtcsv.pro CONFIG+=release DESTDIR=%cd%
- mingw32-make
- qmake ..\example\example.pro CONFIG+=release DESTDIR=%cd%
- mingw32-make
- example.exe
